name: "GitVersion Workflow"
description: "Processes GitVersion"
inputs:
  working-directory:
    description: "The working directory for GitVersion"
    required: true
    default: "."

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool

    - name: Run GitVersion
      run: gitversion > gitversion.json
      env:
        WORKING_DIRECTORY: ${{ inputs.working-directory }}

    - name: Export GitVersion Variables
      run: |
        VERSION=$(cat gitversion.json | jq -r '.NuGetVersion')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      env:
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
