name: Build and Test
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
        matrix:
            dotnet-version: ['6.0.x','7.0.x','8.0.x']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: GitVersion Processing
      uses: ./.github/workflows/gitversion.yml
      with:
        working-directory: . 
        
    - name: Restore Dependencies
      run: dotnet restore --force-evaluate
      
    - name: Build
      run: dotnet build -c Release /p:Version=${{ env.VERSION }}
      
    - name: Test
      run: dotnet test -c Release --no-build
      
    - name: Save Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: "**/TestResults/*.trx"
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: "src/NSKeyedArchive/bin/Release/net*/"