name: Build and Version

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: ./src/NSKeyedArchive

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for GitVersion
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: 5.x
          
      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.11
        
      - name: Display Version
        run: |
          echo "Version: ${{ steps.gitversion.outputs.semVer }}"
          echo "VERSION=${{ steps.gitversion.outputs.semVer }}" >> $GITHUB_ENV
          
      - name: Build
        run: dotnet build -c Release /p:Version=${{ env.VERSION }}
        
      - name: Test
        run: dotnet test -c Release --no-build