name: Build and Test
on:
  push:
    branches: [ "develop", "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Fetch tags
      run: git fetch --tags
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Add Microsoft .NET Repository
      run: |
        wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
             
    - name: Install .NET 6 Runtime
      run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-runtime-6.0
   
    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release
      
    - name: Test
      run: dotnet test -c Release --no-build