name: Build and Test
on:
  push:
    branches: [ "develop", "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Fetch tags
      run: git fetch --tags
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install ASP.NET Core Runtime
      run: sudo apt-get install -y aspnetcore-runtime-6.0 aspnetcore-runtime-7.0
   
    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release
      
    - name: Test
      run: dotnet test -c Release --no-build