# Version: 3.0.0
# Date: 2024-12-21
# Features:
# - Streamlined GitVersion installation
# - Simplified error handling
# - Direct version calculation
# Changes from v2.0.0:
# - Removed redundant installation verification
# - Simplified workspace handling
# Dependencies: 
# - GitVersion.Tool
# - jq

name: GitVersion Workflow

on:
  workflow_call:
    outputs:
      version:
        description: "The calculated version number"
        value: ${{ jobs.calculate-version.outputs.version }}

jobs:
  calculate-version:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool

      - name: Run GitVersion
        id: gitversion
        run: |
          mkdir -p version-info
          # Run GitVersion and capture output
          dotnet-gitversion /output json > version-info/gitversion.json
        
      - name: Set Version Output
        id: set-version
        run: |
          VERSION=$(cat version-info/gitversion.json | jq -r '.NuGetVersion')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Calculated version: $VERSION"
          
      - name: Upload Version Info
        uses: actions/upload-artifact@v3
        with:
          name: version-info
          path: version-info/
          retention-days: 1