name: Publish New Release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Full Clone
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Fetch tags
      run: git fetch --tags
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install ASP.NET Core Runtime
      run: sudo apt-get install -y aspnetcore-runtime-6.0 aspnetcore-runtime-7.0
 
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      
    - name: Pack
      run: dotnet pack src/NSKeyedArchive/NSKeyedArchive.csproj -c Release /p:Version=${VERSION} -o .
      
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json

    - name: Install GitHub Changelog Generator
      run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install github_changelog_generator

    - name: Generate Changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        github_changelog_generator -u anthony-maio -p NSKeyedArchive.NET
        git add CHANGELOG.md
        git commit -m "Update changelog for version ${VERSION}"
        git push origin main
      
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "v${VERSION}" "*.nupkg" --title "Release v${VERSION}" --notes "Automated release of version v${VERSION}."