name: Release to NuGet
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Full Clone
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Fetch tags
      run: git fetch --tags
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Add Microsoft .NET Repository
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https
        wget https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
          
    - name: Install .NET 6 Runtime
      run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-runtime-6.0
 
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      
    - name: Pack
      run: dotnet pack src/NSKeyedArchive/NSKeyedArchive.csproj -c Release /p:Version=${VERSION} -o .
      
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json